# -*- coding: utf-8 -*-
"""Copy of Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14QcMujmmsG3Yf_B0MBr-SJEwtNUFtNw0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeRegressor, plot_tree
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df = pd.read_csv("/content/house prediction.csv")

print(df.head())

print(df.info())

print(df.isnull().sum())

df = df.drop_duplicates()

label_encoder = LabelEncoder()
df["area_type"] = label_encoder.fit_transform(df["area_type"])
df["availability"] = label_encoder.fit_transform(df["availability"])
df["location"] = label_encoder.fit_transform(df["location"])

X = df.drop("price", axis=1)
y = df["price"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=48
)

model = DecisionTreeRegressor(random_state=48)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
print("MAE:", mae)

mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

rmse = np.sqrt(mse)
print("RMSE:", rmse)

r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)

print("Model Performance")
print("------------------------")
print("MAE :", round(mae,2))
print("MSE :", round(mse,2))
print("RMSE :", round(rmse,2))
print("R² Score :", round(r2,2))
print("Accuracy :", round(r2*100,2), "%")

new_house = [[2, 0, 5, 3, 1500, 2, 2]]
prediction = model.predict(new_house)
print("Predicted House Price:", prediction[0], "Lakhs")

plt.figure(figsize=(18,10))
plot_tree(
    model,
    feature_names=X.columns,
    filled=True,
    rounded=True,
    fontsize=8
)

plt.show()

